"use client";

import type { ColumnDef, SortingState } from "@tanstack/react-table";
import { getCoreRowModel, getSortedRowModel, useReactTable } from "@tanstack/react-table";
import { Edit2, Eye, Trash2 } from "lucide-react";
import * as React from "react";

import {
  GmaoBulkSelectBar,
  GmaoRowCheckbox,
  GmaoStandardTable,
  GmaoTablePagination,
} from "@/components/gmao/gmao-table";
import { GMAO_ICON_DELETE, GMAO_ICON_EDIT, GMAO_ICON_VIEW } from "@/components/gmao/table-styles";
import { MaintenanceOrderPdfButton } from "@/components/maintenance-orders/maintenance-order-pdf-button";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import type { MaintenanceOrderRow } from "@/lib/gmao/maintenance-orders-query";
import { formatDateFrShort } from "@/lib/utils/format-date";
import { maintenanceOrderStatusFr } from "@/lib/view/gmao-labels";
import { cn } from "@/lib/utils";

function statusBadgeClass(status: MaintenanceOrderRow["status"]): string {
  switch (status) {
    case "ACTIVE":
      return "bg-blue-50 text-blue-700 border-blue-200";
    case "COMPLETED":
      return "bg-emerald-50 text-emerald-700 border-emerald-200";
    case "CANCELLED":
      return "bg-slate-100 text-slate-600 border-slate-200";
    default:
      return "";
  }
}

type MaintenanceOrdersDataTableProps = {
  orders: MaintenanceOrderRow[];
  selectedIds: Set<string>;
  onSelectedIdsChange: (ids: Set<string>) => void;
  onView: (order: MaintenanceOrderRow) => void;
  onEdit: (order: MaintenanceOrderRow) => void;
  onDelete: (order: MaintenanceOrderRow) => void;
  onBulkDelete: () => void;
  isPending?: boolean;
  readOnly?: boolean;
  pagination?: { page: number; pageCount: number; total: number };
  previousHref?: string;
  nextHref?: string;
};

export function MaintenanceOrdersDataTable({
  orders,
  selectedIds,
  onSelectedIdsChange,
  onView,
  onEdit,
  onDelete,
  onBulkDelete,
  isPending,
  readOnly = false,
  pagination,
  previousHref,
  nextHref,
}: MaintenanceOrdersDataTableProps) {
  const [sorting, setSorting] = React.useState<SortingState>([]);
  const visibleIds = React.useMemo(() => orders.map((o) => o.id), [orders]);
  const allVisibleSelected = visibleIds.length > 0 && visibleIds.every((id) => selectedIds.has(id));
  const someVisibleSelected = visibleIds.some((id) => selectedIds.has(id));

  const toggleAllVisible = React.useCallback(
    (checked: boolean) => {
      onSelectedIdsChange(
        checked ? new Set(visibleIds) : new Set(Array.from(selectedIds).filter((id) => !visibleIds.includes(id))),
      );
    },
    [onSelectedIdsChange, selectedIds, visibleIds],
  );

  const columns = React.useMemo<ColumnDef<MaintenanceOrderRow>[]>(() => {
    const cols: ColumnDef<MaintenanceOrderRow>[] = [];
    if (!readOnly) {
      cols.push({
        id: "select",
        enableSorting: false,
        header: () => (
          <GmaoRowCheckbox
            checked={allVisibleSelected}
            indeterminate={someVisibleSelected && !allVisibleSelected}
            onChange={toggleAllVisible}
            ariaLabel="Sélectionner tous les ordres visibles"
          />
        ),
        cell: ({ row }) => (
          <GmaoRowCheckbox
            checked={selectedIds.has(row.original.id)}
            onChange={(checked) => {
              const next = new Set(selectedIds);
              if (checked) next.add(row.original.id);
              else next.delete(row.original.id);
              onSelectedIdsChange(next);
            }}
            ariaLabel={`Sélectionner ${row.original.reference}`}
          />
        ),
      });
    }
    cols.push(
      {
        accessorKey: "reference",
        header: "Référence",
        cell: ({ row }) => (
          <span className="font-medium text-slate-900">
            {row.original.reference}
            {row.original.autoGenerated ? (
              <Badge variant="outline" className="ml-2 rounded-full font-normal text-[10px]">
                Auto
              </Badge>
            ) : null}
          </span>
        ),
      },
      {
        accessorKey: "plannedDate",
        header: "Date prévue",
        cell: ({ row }) => formatDateFrShort(row.original.plannedDate),
      },
      {
        accessorKey: "logCount",
        header: "Interventions",
        cell: ({ row }) => (
          <span className="tabular-nums text-sm text-slate-700">{row.original.logCount.toLocaleString("fr-FR")}</span>
        ),
      },
      {
        accessorKey: "machineNames",
        header: "Machines",
        cell: ({ row }) => (
          <span className="line-clamp-2 max-w-[220px] text-sm text-slate-600" title={row.original.machineNames}>
            {row.original.machineNames || "—"}
          </span>
        ),
      },
      {
        accessorKey: "status",
        header: "Statut",
        cell: ({ row }) => (
          <Badge variant="outline" className={cn("rounded-full font-medium", statusBadgeClass(row.original.status))}>
            {maintenanceOrderStatusFr(row.original.status)}
          </Badge>
        ),
      },
      {
        id: "actions",
        header: "Actions",
        enableSorting: false,
        cell: ({ row }) => (
          <div className="flex items-center gap-0.5">
            <Button type="button" variant="ghost" size="icon" className={GMAO_ICON_VIEW} onClick={() => onView(row.original)} aria-label="Voir">
              <Eye className="h-4 w-4" />
            </Button>
            {!readOnly ? (
              <>
                {row.original.status !== "COMPLETED" ? (
                  <>
                    <Button type="button" variant="ghost" size="icon" className={GMAO_ICON_EDIT} onClick={() => onEdit(row.original)} aria-label="Modifier">
                      <Edit2 className="h-4 w-4" />
                    </Button>
                    <Button type="button" variant="ghost" size="icon" className={GMAO_ICON_DELETE} onClick={() => onDelete(row.original)} aria-label="Supprimer">
                      <Trash2 className="h-4 w-4" />
                    </Button>
                  </>
                ) : null}
              </>
            ) : null}
            <MaintenanceOrderPdfButton orderId={row.original.id} reference={row.original.reference} size="icon" />
          </div>
        ),
      },
    );
    return cols;
  }, [allVisibleSelected, onDelete, onEdit, onSelectedIdsChange, onView, readOnly, selectedIds, someVisibleSelected, toggleAllVisible]);

  const table = useReactTable({
    data: orders,
    columns,
    state: { sorting },
    onSortingChange: setSorting,
    getCoreRowModel: getCoreRowModel(),
    getSortedRowModel: getSortedRowModel(),
  });

  return (
    <div className="space-y-3">
      {!readOnly ? <GmaoBulkSelectBar count={selectedIds.size} onBulkDelete={onBulkDelete} /> : null}
      <GmaoStandardTable
        table={table}
        emptyMessage="Aucun ordre de maintenance journalier."
        selectedIdSet={selectedIds}
        getRowId={(row) => row.id}
        isPending={isPending}
      />
      <GmaoTablePagination
        total={pagination?.total ?? orders.length}
        noun="résultat(s)"
        page={pagination?.page}
        pageCount={pagination?.pageCount}
        previousHref={previousHref}
        nextHref={nextHref}
      />
    </div>
  );
}
