import {
  AlertSeverity,
  AlertType,
  InterventionType,
  type Prisma,
  type PrismaClient,
} from "@prisma/client";

import { calendarDayKey } from "@/lib/gmao/intervention-status";
import { formatDateFrShort } from "@/lib/utils/format-date";

type Db = PrismaClient | Prisma.TransactionClient;

export type DailyOrderLink = {
  orderId: string;
  reference: string;
  dayKey: string;
  created: boolean;
};

const DAILY_REF = /^OM-(\d{4}-\d{2}-\d{2})$/;

export function dayBounds(dayKey: string): { start: Date; end: Date; plannedDate: Date } {
  const plannedDate = new Date(`${dayKey}T00:00:00.000Z`);
  const start = plannedDate;
  const end = new Date(plannedDate.getTime() + 24 * 60 * 60 * 1000);
  return { start, end, plannedDate };
}

export function dailyOrderDayKey(order: { dayKey: string | null; reference: string }): string | null {
  if (order.dayKey && DAILY_REF.test(`OM-${order.dayKey}`)) return order.dayKey;
  const match = order.reference.match(DAILY_REF);
  return match?.[1] ?? null;
}

function orderTypeFromLog(type: InterventionType): InterventionType {
  return type === InterventionType.AMELIORATION ? InterventionType.PREVENTIVE : type;
}

function mergeOrderType(current: InterventionType, incoming: InterventionType): InterventionType {
  const next = orderTypeFromLog(incoming);
  if (current === next) return current;
  if (current === InterventionType.PREVENTIVE || next === InterventionType.PREVENTIVE) {
    return InterventionType.PREVENTIVE;
  }
  return next;
}

export async function ensureLogsLinkedToDailyOrder(db: Db, orderId: string, dayKey: string): Promise<number> {
  const { start, end } = dayBounds(dayKey);
  const result = await db.maintenanceLog.updateMany({
    where: {
      date: { gte: start, lt: end },
      NOT: { maintenanceOrderId: orderId },
    },
    data: { maintenanceOrderId: orderId },
  });
  return result.count;
}

async function findOrCreateDailyOrder(
  db: Db,
  input: {
    dayKey: string;
    type: InterventionType;
    notify?: boolean;
    logId?: string;
  },
): Promise<{ order: { id: string; reference: string; dayKey: string | null; interventionType: InterventionType }; created: boolean }> {
  const dayKey = input.dayKey;
  const { plannedDate } = dayBounds(dayKey);
  let created = false;
  let order = await db.maintenanceOrder.findUnique({ where: { dayKey } });

  if (!order) {
    order = await db.maintenanceOrder.findUnique({ where: { reference: `OM-${dayKey}` } });
    if (order && !order.dayKey) {
      order = await db.maintenanceOrder.update({
        where: { id: order.id },
        data: { dayKey },
      });
    }
  }

  if (!order) {
    try {
      order = await db.maintenanceOrder.create({
        data: {
          reference: `OM-${dayKey}`,
          plannedDate,
          dayKey,
          autoGenerated: true,
          interventionType: orderTypeFromLog(input.type),
          observationComment: `Ordre journalier unique du ${formatDateFrShort(plannedDate.toISOString())} : interventions préventives et correctives de la journée.`,
        },
      });
      created = true;
    } catch {
      order = await db.maintenanceOrder.findUnique({ where: { dayKey } });
      if (!order) {
        order = await db.maintenanceOrder.findUnique({ where: { reference: `OM-${dayKey}` } });
      }
      if (!order) throw new Error(`Impossible de créer l'ordre du ${dayKey}.`);
    }

    if (created && input.notify) {
      await db.gmaoAlert.create({
        data: {
          type: AlertType.MAINTENANCE_ORDER,
          severity: AlertSeverity.INFO,
          title: `Nouvel ordre de maintenance ${order.reference}`,
          message: `Un OM journalier a été créé pour le ${formatDateFrShort(plannedDate.toISOString())} (préventif et correctif).`,
          metadata: { orderId: order.id, dayKey, logId: input.logId } as Prisma.InputJsonValue,
        },
      });
    }
  } else {
    const merged = mergeOrderType(order.interventionType, input.type);
    if (merged !== order.interventionType || !order.dayKey) {
      order = await db.maintenanceOrder.update({
        where: { id: order.id },
        data: { interventionType: merged, dayKey: order.dayKey ?? dayKey },
      });
    }
  }

  return { order, created };
}

export async function attachLogToDailyOrder(
  db: Db,
  input: {
    logId: string;
    date: Date;
    type: InterventionType;
    machineId: string;
    existingLineId?: string | null;
    preventiveCleaning?: boolean | null;
    preventiveLubrication?: boolean | null;
    preventiveOil?: boolean | null;
    preventiveControl?: boolean | null;
    preventiveNonConforme?: boolean | null;
    notify?: boolean;
  },
): Promise<DailyOrderLink> {
  const dayKey = calendarDayKey(input.date);

  if (input.existingLineId) {
    const line = await db.maintenanceOrderLine.findUnique({
      where: { id: input.existingLineId },
      include: { maintenanceOrder: true },
    });
    if (line) {
      await db.maintenanceLog.update({
        where: { id: input.logId },
        data: { maintenanceOrderId: line.maintenanceOrderId },
      });
      const dailyKey = dailyOrderDayKey(line.maintenanceOrder);
      if (dailyKey) {
        await ensureLogsLinkedToDailyOrder(db, line.maintenanceOrderId, dailyKey);
      }
      return {
        orderId: line.maintenanceOrderId,
        reference: line.maintenanceOrder.reference,
        dayKey: dailyKey ?? dayKey,
        created: false,
      };
    }
  }

  let created = false;
  const found = await findOrCreateDailyOrder(db, {
    dayKey,
    type: input.type,
    notify: input.notify,
    logId: input.logId,
  });
  created = found.created;
  const order = found.order;

  await db.maintenanceLog.update({
    where: { id: input.logId },
    data: { maintenanceOrderId: order.id },
  });
  await ensureLogsLinkedToDailyOrder(db, order.id, dayKey);

  if (input.type === InterventionType.PREVENTIVE) {
    const existingLine = await db.maintenanceOrderLine.findUnique({
      where: {
        maintenanceOrderId_machineId: { maintenanceOrderId: order.id, machineId: input.machineId },
      },
      include: { maintenanceLog: { select: { id: true } } },
    });

    if (!existingLine) {
      const line = await db.maintenanceOrderLine.create({
        data: {
          maintenanceOrderId: order.id,
          machineId: input.machineId,
          taskNettoyage: Boolean(input.preventiveCleaning),
          taskGraissage: Boolean(input.preventiveLubrication),
          taskHuile: Boolean(input.preventiveOil),
          taskControl: Boolean(input.preventiveControl),
          taskNonConforme: Boolean(input.preventiveNonConforme),
        },
      });
      await db.maintenanceLog.update({
        where: { id: input.logId },
        data: { maintenanceOrderLineId: line.id },
      });
    } else if (!existingLine.maintenanceLog) {
      await db.maintenanceLog.update({
        where: { id: input.logId },
        data: { maintenanceOrderLineId: existingLine.id },
      });
    }
  }

  return { orderId: order.id, reference: order.reference, dayKey, created };
}

export async function syncDailyMaintenanceOrders(db: PrismaClient): Promise<{ days: number; created: number; linked: number }> {
  const logs = await db.maintenanceLog.findMany({
    where: { maintenanceOrderId: null },
    select: {
      id: true,
      date: true,
      type: true,
      machineId: true,
      preventiveCleaning: true,
      preventiveLubrication: true,
      preventiveOil: true,
      preventiveControl: true,
      preventiveNonConforme: true,
    },
  });

  if (logs.length === 0) {
    const dailiesOnly = await db.maintenanceOrder.findMany({
      where: { dayKey: { not: null } },
      select: { id: true, dayKey: true },
    });
    let relinked = 0;
    for (const order of dailiesOnly) {
      if (!order.dayKey) continue;
      relinked += await ensureLogsLinkedToDailyOrder(db, order.id, order.dayKey);
    }
    return { days: dailiesOnly.length, created: 0, linked: relinked };
  }

  const byDay = new Map<string, typeof logs>();
  for (const log of logs) {
    const key = calendarDayKey(log.date);
    const list = byDay.get(key);
    if (list) list.push(log);
    else byDay.set(key, [log]);
  }

  const dayKeys = Array.from(byDay.keys());
  const existing = await db.maintenanceOrder.findMany({
    where: {
      OR: [{ dayKey: { in: dayKeys } }, { reference: { in: dayKeys.map((k) => `OM-${k}`) } }],
    },
    select: { id: true, dayKey: true, reference: true, interventionType: true },
  });

  const byKey = new Map<string, (typeof existing)[number]>();
  for (const order of existing) {
    if (order.dayKey) byKey.set(order.dayKey, order);
    const refDay = order.reference.startsWith("OM-") ? order.reference.slice(3) : null;
    if (refDay && !byKey.has(refDay)) byKey.set(refDay, order);
  }

  const toCreate: {
    id: string;
    reference: string;
    plannedDate: Date;
    dayKey: string;
    autoGenerated: boolean;
    interventionType: InterventionType;
    observationComment: string;
  }[] = [];

  for (const dayKey of dayKeys) {
    if (byKey.has(dayKey)) continue;
    const group = byDay.get(dayKey)!;
    const hasPreventive = group.some((l) => l.type === InterventionType.PREVENTIVE);
    const { plannedDate } = dayBounds(dayKey);
    toCreate.push({
      id: `om_${dayKey}_${group[0]!.id.slice(-8)}`,
      reference: `OM-${dayKey}`,
      plannedDate,
      dayKey,
      autoGenerated: true,
      interventionType: hasPreventive ? InterventionType.PREVENTIVE : orderTypeFromLog(group[0]!.type),
      observationComment: `Ordre journalier généré automatiquement pour le ${formatDateFrShort(plannedDate.toISOString())} (préventif et/ou correctif).`,
    });
  }

  if (toCreate.length) {
    await db.maintenanceOrder.createMany({ data: toCreate, skipDuplicates: true });
    const createdRows = await db.maintenanceOrder.findMany({
      where: { dayKey: { in: toCreate.map((o) => o.dayKey) } },
      select: { id: true, dayKey: true, reference: true, interventionType: true },
    });
    for (const order of createdRows) {
      if (order.dayKey) byKey.set(order.dayKey, order);
    }
  }

  const linePayloads: {
    maintenanceOrderId: string;
    machineId: string;
    taskNettoyage: boolean;
    taskGraissage: boolean;
    taskHuile: boolean;
    taskControl: boolean;
    taskNonConforme: boolean;
  }[] = [];

  let linked = 0;
  for (const [dayKey, group] of Array.from(byDay.entries())) {
    const order = byKey.get(dayKey);
    if (!order) continue;
    const ids = group.map((l) => l.id);
    for (let i = 0; i < ids.length; i += 500) {
      await db.maintenanceLog.updateMany({
        where: { id: { in: ids.slice(i, i + 500) } },
        data: { maintenanceOrderId: order.id },
      });
    }
    linked += group.length;
    linked += await ensureLogsLinkedToDailyOrder(db, order.id, dayKey);

    const merged = group.reduce(
      (acc, log) => mergeOrderType(acc, log.type),
      order.interventionType,
    );
    if (merged !== order.interventionType) {
      await db.maintenanceOrder.update({
        where: { id: order.id },
        data: { interventionType: merged, dayKey: order.dayKey ?? dayKey },
      });
    }

    const seen = new Set<string>();
    for (const log of group) {
      if (log.type !== InterventionType.PREVENTIVE) continue;
      if (seen.has(log.machineId)) continue;
      seen.add(log.machineId);
      linePayloads.push({
        maintenanceOrderId: order.id,
        machineId: log.machineId,
        taskNettoyage: Boolean(log.preventiveCleaning),
        taskGraissage: Boolean(log.preventiveLubrication),
        taskHuile: Boolean(log.preventiveOil),
        taskControl: Boolean(log.preventiveControl),
        taskNonConforme: Boolean(log.preventiveNonConforme),
      });
    }
  }

  for (let i = 0; i < linePayloads.length; i += 500) {
    await db.maintenanceOrderLine.createMany({
      data: linePayloads.slice(i, i + 500),
      skipDuplicates: true,
    });
  }

  const dailies = await db.maintenanceOrder.findMany({
    where: { dayKey: { not: null } },
    select: { id: true, dayKey: true },
  });
  for (const order of dailies) {
    if (!order.dayKey) continue;
    linked += await ensureLogsLinkedToDailyOrder(db, order.id, order.dayKey);
  }

  return { days: byDay.size, created: toCreate.length, linked };
}
