import type { MaintenanceOrderStatus, Prisma } from "@prisma/client";
import { unstable_cache } from "next/cache";

import { CACHE_TAGS } from "@/lib/cache/tags";
import type { PaginatedResult } from "@/lib/db/pagination";
import { prisma } from "@/lib/db/prisma";

export type MaintenanceOrderRow = {
  id: string;
  reference: string;
  plannedDate: string;
  status: MaintenanceOrderStatus;
  observationComment: string | null;
  managerApproval: string | null;
  autoGenerated: boolean;
  logCount: number;
  machineCount: number;
  machineNames: string;
  pendingLineCount: number;
  createdAt: string;
};

export const MAINTENANCE_ORDERS_PAGE_SIZE = 10;

const orderListSelect = {
  id: true,
  reference: true,
  plannedDate: true,
  status: true,
  observationComment: true,
  managerApproval: true,
  createdAt: true,
  autoGenerated: true,
  _count: { select: { logs: true } },
  lines: {
    select: {
      id: true,
      machine: { select: { name: true } },
      maintenanceLog: { select: { id: true } },
    },
  },
} as const;

type OrderListRow = {
  id: string;
  reference: string;
  plannedDate: Date;
  status: MaintenanceOrderStatus;
  observationComment: string | null;
  managerApproval: string | null;
  createdAt: Date;
  autoGenerated: boolean;
  _count: { logs: number };
  lines: { id: string; machine: { name: string }; maintenanceLog: { id: string } | null }[];
};

function mapOrderRows(rows: OrderListRow[]): MaintenanceOrderRow[] {
  return rows.map((o) => {
    const pending = o.lines.filter((l) => !l.maintenanceLog).length;
    return {
      id: o.id,
      reference: o.reference,
      plannedDate: o.plannedDate.toISOString(),
      status: o.status,
      observationComment: o.observationComment,
      managerApproval: o.managerApproval,
      machineCount: o.lines.length,
      logCount: o._count.logs,
      autoGenerated: o.autoGenerated,
      machineNames: o.lines.map((l) => l.machine.name).join(", "),
      pendingLineCount: pending,
      createdAt: o.createdAt.toISOString(),
    };
  });
}

function buildOrdersWhere(filters?: {
  q?: string;
  status?: string;
  machineId?: string;
  dateFrom?: string;
  dateTo?: string;
}): Prisma.MaintenanceOrderWhereInput {
  const and: Prisma.MaintenanceOrderWhereInput[] = [];
  const q = filters?.q?.trim();
  if (q) {
    and.push({
      OR: [
        { reference: { contains: q, mode: "insensitive" } },
        { id: { contains: q, mode: "insensitive" } },
      ],
    });
  }
  if (filters?.status && filters.status !== "ALL") {
    and.push({ status: filters.status as MaintenanceOrderStatus });
  }
  if (filters?.machineId && filters.machineId !== "ALL") {
    and.push({
      OR: [
        { lines: { some: { machineId: filters.machineId } } },
        { logs: { some: { machineId: filters.machineId } } },
      ],
    });
  }
  if (filters?.dateFrom) {
    and.push({ plannedDate: { gte: new Date(`${filters.dateFrom}T00:00:00.000`) } });
  }
  if (filters?.dateTo) {
    and.push({ plannedDate: { lte: new Date(`${filters.dateTo}T23:59:59.999`) } });
  }
  return and.length ? { AND: and } : {};
}

export type MaintenanceOrderListFilters = {
  q?: string;
  status?: string;
  machineId?: string;
  dateFrom?: string;
  dateTo?: string;
};

export async function fetchMaintenanceOrdersPage(
  page = 1,
  pageSize = MAINTENANCE_ORDERS_PAGE_SIZE,
  filters?: MaintenanceOrderListFilters,
): Promise<PaginatedResult<MaintenanceOrderRow>> {
  const safePage = Math.max(1, page);
  const safeLimit = Math.max(1, Math.min(pageSize, 50));
  const skip = (safePage - 1) * safeLimit;
  const where = buildOrdersWhere(filters);

  const [total, rows] = await Promise.all([
    prisma.maintenanceOrder.count({ where }),
    prisma.maintenanceOrder.findMany({
      where,
      skip,
      take: safeLimit,
      orderBy: [{ plannedDate: "desc" }, { createdAt: "desc" }],
      select: orderListSelect,
    }),
  ]);

  return {
    items: mapOrderRows(rows),
    total,
    page: safePage,
    pageSize: safeLimit,
    pageCount: Math.max(1, Math.ceil(total / safeLimit) || 1),
  };
}

/** @deprecated Utiliser fetchMaintenanceOrdersPage — conserve la 1re page pour compatibilité. */
export async function fetchMaintenanceOrders(): Promise<MaintenanceOrderRow[]> {
  const page = await fetchMaintenanceOrdersPage(1, MAINTENANCE_ORDERS_PAGE_SIZE);
  return page.items;
}

export function getMaintenanceOrdersCached(
  page = 1,
  pageSize = MAINTENANCE_ORDERS_PAGE_SIZE,
  filters?: MaintenanceOrderListFilters,
) {
  const q = filters?.q ?? "";
  const status = filters?.status ?? "ALL";
  const machineId = filters?.machineId ?? "ALL";
  const dateFrom = filters?.dateFrom ?? "";
  const dateTo = filters?.dateTo ?? "";
  return unstable_cache(
    () => fetchMaintenanceOrdersPage(page, pageSize, filters),
    [CACHE_TAGS.maintenanceOrders, "v5", String(page), String(pageSize), q, status, machineId, dateFrom, dateTo],
    { revalidate: 60, tags: [CACHE_TAGS.maintenanceOrders] },
  )();
}

export type ActiveMaintenanceOrderOption = {
  id: string;
  reference: string;
  plannedDate: string;
  lines: {
    lineId: string;
    machineId: string;
    machineName: string;
    taskNettoyage: boolean;
    taskGraissage: boolean;
    taskHuile: boolean;
    taskControl: boolean;
    taskNonConforme: boolean;
  }[];
};

export async function fetchActiveMaintenanceOrders(): Promise<ActiveMaintenanceOrderOption[]> {
  const rows = await prisma.maintenanceOrder.findMany({
    where: { status: "ACTIVE" },
    orderBy: { plannedDate: "asc" },
    take: 30,
    select: {
      id: true,
      reference: true,
      plannedDate: true,
      lines: {
        where: { maintenanceLog: { is: null } },
        select: {
          id: true,
          machineId: true,
          taskNettoyage: true,
          taskGraissage: true,
          taskHuile: true,
          taskControl: true,
          taskNonConforme: true,
          machine: { select: { id: true, name: true } },
        },
      },
    },
  });

  return rows
    .filter((o) => o.lines.length > 0)
    .map((o) => ({
      id: o.id,
      reference: o.reference,
      plannedDate: o.plannedDate.toISOString(),
      lines: o.lines.map((l) => ({
        lineId: l.id,
        machineId: l.machineId,
        machineName: l.machine.name,
        taskNettoyage: l.taskNettoyage,
        taskGraissage: l.taskGraissage,
        taskHuile: l.taskHuile,
        taskControl: l.taskControl,
        taskNonConforme: l.taskNonConforme,
      })),
    }));
}
