import {
  AlertSeverity,
  AlertType,
  InterventionType,
  type Prisma,
  type PrismaClient,
} from "@prisma/client";

import { calendarDayKey } from "@/lib/gmao/intervention-status";
import { formatDateFrShort } from "@/lib/utils/format-date";

type Db = PrismaClient | Prisma.TransactionClient;

export type DailyOrderLink = {
  orderId: string;
  reference: string;
  dayKey: string;
  created: boolean;
};

function dayBounds(dayKey: string): { start: Date; end: Date; plannedDate: Date } {
  const plannedDate = new Date(`${dayKey}T00:00:00.000Z`);
  const start = plannedDate;
  const end = new Date(plannedDate.getTime() + 24 * 60 * 60 * 1000);
  return { start, end, plannedDate };
}

function orderTypeFromLog(type: InterventionType): InterventionType {
  return type === InterventionType.AMELIORATION ? InterventionType.PREVENTIVE : type;
}

function mergeOrderType(current: InterventionType, incoming: InterventionType): InterventionType {
  const next = orderTypeFromLog(incoming);
  if (current === next) return current;
  if (current === InterventionType.PREVENTIVE || next === InterventionType.PREVENTIVE) {
    return InterventionType.PREVENTIVE;
  }
  return next;
}

export async function attachLogToDailyOrder(
  db: Db,
  input: {
    logId: string;
    date: Date;
    type: InterventionType;
    machineId: string;
    existingLineId?: string | null;
    preventiveCleaning?: boolean | null;
    preventiveLubrication?: boolean | null;
    preventiveOil?: boolean | null;
    preventiveControl?: boolean | null;
    preventiveNonConforme?: boolean | null;
    notify?: boolean;
  },
): Promise<DailyOrderLink> {
  const dayKey = calendarDayKey(input.date);
  const { start, end, plannedDate } = dayBounds(dayKey);

  if (input.existingLineId) {
    const line = await db.maintenanceOrderLine.findUnique({
      where: { id: input.existingLineId },
      include: { maintenanceOrder: true },
    });
    if (line) {
      if (!line.maintenanceOrder.dayKey) {
        await db.maintenanceOrder.update({
          where: { id: line.maintenanceOrderId },
          data: { dayKey },
        });
      }
      await db.maintenanceLog.update({
        where: { id: input.logId },
        data: { maintenanceOrderId: line.maintenanceOrderId },
      });
      return {
        orderId: line.maintenanceOrderId,
        reference: line.maintenanceOrder.reference,
        dayKey: line.maintenanceOrder.dayKey ?? dayKey,
        created: false,
      };
    }
  }

  let created = false;
  let order = await db.maintenanceOrder.findUnique({ where: { dayKey } });

  if (!order) {
    order = await db.maintenanceOrder.findFirst({
      where: {
        OR: [{ reference: `OM-${dayKey}` }, { plannedDate: { gte: start, lt: end } }],
      },
      orderBy: { createdAt: "asc" },
    });
    if (order && !order.dayKey) {
      order = await db.maintenanceOrder.update({
        where: { id: order.id },
        data: { dayKey },
      });
    }
  }

  if (!order) {
    try {
      order = await db.maintenanceOrder.create({
        data: {
          reference: `OM-${dayKey}`,
          plannedDate,
          dayKey,
          autoGenerated: true,
          interventionType: orderTypeFromLog(input.type),
          observationComment: `Ordre journalier généré automatiquement pour le ${formatDateFrShort(plannedDate.toISOString())} (préventif et/ou correctif).`,
        },
      });
      created = true;
    } catch {
      order = await db.maintenanceOrder.findUnique({ where: { dayKey } });
      if (!order) {
        order = await db.maintenanceOrder.findUnique({ where: { reference: `OM-${dayKey}` } });
      }
      if (!order) throw new Error(`Impossible de créer l'ordre du ${dayKey}.`);
    }

    if (created && input.notify) {
      await db.gmaoAlert.create({
        data: {
          type: AlertType.MAINTENANCE_ORDER,
          severity: AlertSeverity.INFO,
          title: `Nouvel ordre de maintenance ${order.reference}`,
          message: `Un OM a été créé automatiquement pour le ${formatDateFrShort(plannedDate.toISOString())} à partir des interventions du jour.`,
          metadata: { orderId: order.id, dayKey, logId: input.logId } as Prisma.InputJsonValue,
        },
      });
    }
  } else {
    const merged = mergeOrderType(order.interventionType, input.type);
    if (merged !== order.interventionType || !order.dayKey) {
      order = await db.maintenanceOrder.update({
        where: { id: order.id },
        data: { interventionType: merged, dayKey: order.dayKey ?? dayKey },
      });
    }
  }

  await db.maintenanceLog.update({
    where: { id: input.logId },
    data: { maintenanceOrderId: order.id },
  });

  if (input.existingLineId) {
    return { orderId: order.id, reference: order.reference, dayKey, created };
  }

  const existingLine = await db.maintenanceOrderLine.findUnique({
    where: {
      maintenanceOrderId_machineId: { maintenanceOrderId: order.id, machineId: input.machineId },
    },
    include: { maintenanceLog: { select: { id: true } } },
  });

  if (!existingLine) {
    const line = await db.maintenanceOrderLine.create({
      data: {
        maintenanceOrderId: order.id,
        machineId: input.machineId,
        taskNettoyage: Boolean(input.preventiveCleaning),
        taskGraissage: Boolean(input.preventiveLubrication),
        taskHuile: Boolean(input.preventiveOil),
        taskControl: Boolean(input.preventiveControl),
        taskNonConforme: Boolean(input.preventiveNonConforme),
      },
    });
    await db.maintenanceLog.update({
      where: { id: input.logId },
      data: { maintenanceOrderLineId: line.id },
    });
  } else if (!existingLine.maintenanceLog) {
    await db.maintenanceLog.update({
      where: { id: input.logId },
      data: { maintenanceOrderLineId: existingLine.id },
    });
  }

  return { orderId: order.id, reference: order.reference, dayKey, created };
}

export async function syncDailyMaintenanceOrders(db: PrismaClient): Promise<{ days: number; created: number; linked: number }> {
  const logs = await db.maintenanceLog.findMany({
    where: { maintenanceOrderId: null },
    select: {
      id: true,
      date: true,
      type: true,
      machineId: true,
      preventiveCleaning: true,
      preventiveLubrication: true,
      preventiveOil: true,
      preventiveControl: true,
      preventiveNonConforme: true,
    },
  });

  const byDay = new Map<string, typeof logs>();
  for (const log of logs) {
    const key = calendarDayKey(log.date);
    const list = byDay.get(key);
    if (list) list.push(log);
    else byDay.set(key, [log]);
  }

  let created = 0;
  let linked = 0;

  for (const [dayKey, group] of byDay) {
    const { start, end, plannedDate } = dayBounds(dayKey);
    const hasPreventive = group.some((l) => l.type === InterventionType.PREVENTIVE);
    const orderType = hasPreventive ? InterventionType.PREVENTIVE : orderTypeFromLog(group[0]!.type);

    let order = await db.maintenanceOrder.findUnique({ where: { dayKey } });
    if (!order) {
      order = await db.maintenanceOrder.findFirst({
        where: { OR: [{ reference: `OM-${dayKey}` }, { plannedDate: { gte: start, lt: end } }] },
        orderBy: { createdAt: "asc" },
      });
    }

    if (!order) {
      order = await db.maintenanceOrder.create({
        data: {
          reference: `OM-${dayKey}`,
          plannedDate,
          dayKey,
          autoGenerated: true,
          interventionType: orderType,
          observationComment: `Ordre journalier généré automatiquement pour le ${formatDateFrShort(plannedDate.toISOString())} (préventif et/ou correctif).`,
        },
      });
      created += 1;
    } else {
      await db.maintenanceOrder.update({
        where: { id: order.id },
        data: {
          dayKey: order.dayKey ?? dayKey,
          interventionType: mergeOrderType(order.interventionType, orderType),
        },
      });
    }

    await db.maintenanceLog.updateMany({
      where: { id: { in: group.map((l) => l.id) } },
      data: { maintenanceOrderId: order.id },
    });
    linked += group.length;

    const byMachine = new Map<string, (typeof logs)[number]>();
    for (const log of group) {
      if (!byMachine.has(log.machineId)) byMachine.set(log.machineId, log);
    }

    for (const [machineId, sample] of byMachine) {
      await db.maintenanceOrderLine.upsert({
        where: {
          maintenanceOrderId_machineId: { maintenanceOrderId: order.id, machineId },
        },
        create: {
          maintenanceOrderId: order.id,
          machineId,
          taskNettoyage: Boolean(sample.preventiveCleaning),
          taskGraissage: Boolean(sample.preventiveLubrication),
          taskHuile: Boolean(sample.preventiveOil),
          taskControl: Boolean(sample.preventiveControl),
          taskNonConforme: Boolean(sample.preventiveNonConforme),
        },
        update: {},
      });
    }
  }

  return { days: byDay.size, created, linked };
}
